version: "3.8"
services:
  postgres:
    image: postgres:13
    container_name: radix
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - radix_network

volumes:
  postgres_data:

networks:
  radix_network:
    driver: bridge
